language: java

jdk:
  - oraclejdk8

branches:
  only:
  - master
  - develop

cache:
  directories:
    - $HOME/.m2

addons:
  sonarqube:
    token:
      secure: ${SONAR_TOKEN}

services:
  - mongodb

script: mvn clean install sonar:sonar -Dsonar.cpd.exclusions=**/*Dto.java

after_script:
  - echo "<settings><servers><server><id>github</id><username>\${env.GIT_HUB_USER}</username><password>\${env.GIT_HUB_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy -e --settings ~/settings.xml
