app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey

server:
  port: ${PORT:8380}

spring:
  profiles:
    active: "dev"
  data:
    mongodb:
      host: mongo
      database: chore_tracker

# Expose actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
    pattern:
      file: "%-5level - %replace(%msg){'[\r\n]', ''}%n"
      console: "%-5level - %replace(%msg){'[\r\n]', ''}%n"
    level:
      org.springframework: INFO
      org.hibernate: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    hostname: chore-tracker-service
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart

ribbon:
  eureka:
    enabled: true

---

spring:
  profiles: dev

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

