app:
  jwtExpirationInMs: 604800000
  jwtSecret: JWTSuperSecretKey

server:
  port: ${PORT:8380}
  servlet:
    context-path: /v1/api

spring:
  data:
    mongodb:
      host: mongo
      database: chore_tracker

logging:
    pattern:
      file: "%-5level - %replace(%msg){'[\r\n]', ''}%n"
      console: "%-5level - %replace(%msg){'[\r\n]', ''}%n"
    level:
      org.springframework: INFO
      org.hibernate: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true
